# 1. Configuración de la conexión [cite: 1766-1768]
spring.datasource.url=jdbc:mysql://localhost:3306/centro_deportivo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin

# 2. Driver de MySQL [cite: 1783-1785]
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Magia de Hibernate (DDL-AUTO) [cite: 1802, 1814]
spring.jpa.hibernate.ddl-auto=update

# 4. Ver qué está pasando [cite: 1806-1809]
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true